name: CI

on:
  # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
  # Existing codes likely still have "master" as the primary branch
  # Both are tracked here to keep legacy and new codes working
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


defaults:
  run:
    shell: bash -l {0}


jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]  # , windows-latest
        python-version: ["3.10", "3.11", "3.12"]
        install-networkx: [true, false]

    steps:
    - uses: actions/checkout@v3
    - name: Additional info about the build
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Set up extra packages
      run: |
        EXTRA_CONDA_PACKAGES=""
        if [[ ${{ matrix.install-networkx }} == "true" ]]; then
          EXTRA_CONDA_PACKAGES+=" networkx"
        fi
        echo "EXTRA_CONDA_PACKAGES=$EXTRA_CONDA_PACKAGES" >> $GITHUB_ENV


    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: devtools/conda-envs/base_env.yaml
        create-args: python=${{ matrix.python-version }} ${{ env.EXTRA_CONDA_PACKAGES }}

    - name: Install package
      run: |
        pip install -e .


    - name: Run tests
      run: |
        pytest -v --cov=lipyds --cov-report=xml --color=yes lipyds/tests/

    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
